# Generated by Django 4.2.7 on 2023-11-29 22:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("data", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="UsageAnalysis",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("analysis_start_date", models.DateField()),
                ("analysis_end_date", models.DateField()),
                ("date_created", models.DateField(auto_now_add=True)),
                ("assumed_rate", models.FloatField()),
                ("actual_rate", models.FloatField()),
                (
                    "consumable",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="data.consumable",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.RESTRICT,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
