classDiagram
  class usage {
  }
  class Rater {
  }
  class admin {
  }
  class apps {
  }
  class charts {
  }
  class migrations {
  }
  class 0001_initial {
  }
  class models {
  }
  class tests {
  }
  class urls {
  }
  class views {
  }
